project:
  type: website
  output-dir: docs

website:
  title: "Dr. Roman Kessler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tools.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# for GitHub actions: automatical rendering
execute:
  freeze: auto

