project:
  type: website
  output-dir: docs

website:
  title: "Dr. Roman Kessler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - talks.qmd
      - tools.qmd
      - text: Blog
        href: https://substack.com/home/post/p-147367144?r=3ild5k&utm_campaign=post&utm_medium=web
      #- videos.qmd

format:
  html:
    theme: flatly
# theme: cosmo
    css: styles.css
    toc: true

# for GitHub actions: automatical rendering
execute:
  freeze: auto

